server:
  port: 8002

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Yqh19970717
    username: root
    url: jdbc:mysql://123.56.6.157:3306/testSQL?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true

mybatis:
  type-aliases-package: com.neo.model


