server:
  port: 30480

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Yqh19970717
    username: root
    url: jdbc:mysql://123.56.6.157:3306/testSQL?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
  redis:
    database: 0
    host: 127.0.0.1
    password: QQ2244355530
    timeout: 1000
    jedis:
      pool:
        max-wait: 1000
        max-active: 50
        max-idle: 50
    port: 6379

mybatis:
  type-aliases-package: com.neo.model

