server:
  port: 30485

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: yqh
    url: jdbc:mysql://81.70.239.217:3306/testSQL?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
  redis:
    database: 0
    host: 81.70.239.217
    password: QQ@!22444355530
    timeout: 1000
    jedis:
      pool:
        max-wait: 1000
        max-active: 50
        max-idle: 50
    port: 6379

mybatis:
  type-aliases-package: com.neo.model

